### ISSUE TITLE
Feature Request: Dead Body Interaction 

### ISSUE THREAD

**Issue by Pvtsplodingpies** [Brecon1/5thCavMod#4]
**Issue**
I personally hate the Arma Interaction menu and have died many times, simply by accidently grabbing a weapon and dropping my own on accident when attempting to pick AT or even access a corpse's inventory. 
**Request**
I would really appreciate our own system of extended interaction similar to the mod below.
**Additional context**
https://steamcommunity.com/sharedfiles/filedetails/?id=1376867375

**Comment by Brecon1** [comment]
Can you be more specific about the request as it sounds you just want the mod you linked
If you do, just use the mod.
